### ISSUE TITLE
initialSell false

### ISSUE THREAD

**Issue by TheRafaelSantos** [lagoanova/bitPreco-trading-arbitrage#1]
Opá! Parabéns pelo projeto, muito bacana. estava dando realizando alguns teste e cheguei na tela abaixo.
Não reconhece os saldos em ambiente de teste e initialSell sempre fica como false.

![image](https://user-images.githubusercontent.com/47929225/202832027-5f24fbf8-55d2-4dac-bdcb-27864b731853.png)

**Comment by ghostnetrn** [comment]
Oi, obrigado!

Atualiza a url abaixo acrescentando https:
API_SIMULADOR=http**s**://api-simulator.bitpreco.com/trading/

Lembra de criar as credenciais de teste no site https://simulador.bitpreco.com/ e acrescentar no .env

**Comment by TheRafaelSantos** [comment]
Boa! consegui resolver, realmente faltava um S e agora estou utilizando a versão "bitPreco-trading-arbitrage-2-com-initialSell" no entanto mesmo com o .env 100% preenchido e telegram já rodando. o robô ainda não está executando compras e vendas nem no modo teste nem em produção. Esse bot ainda está em desenvolvimento ou preciso fazer mais algumas configurações além de instalar "npm i" e convfigurar o .env ?


![image](https://user-images.githubusercontent.com/47929225/202880207-34ddb5d4-75fc-41fa-b21e-803f18f2f6f9.png)

**Comment by ghostnetrn** [comment]
O bot só vai pegar oportunidades de arbitragem quando a variação de preço (compra/venda) for maior do que o MIN_PROFIT_PERCENT configurado no .env

**Comment by itxtoledo** [comment]
Só um aviso, diferente do Biscoint que funcionava por meio de offers, a BitPreço possui um livro de ordens padrão e uma match engine, via de regra uma match engine não deve deixar uma ordem de compra ter um preço maior que uma ordem de venda existir no book, automaticamente a ordem seria executada a mercado, desse modo nunca irá existir arbitragem.

Para quem usava a versão do robô que eu escrevi para o Biscoint eu ja avisei em meus grupos sobre isso, vocês mesmos irão constatar e entender quando passar algumas semanas sem o robô ter executado nenhuma operação.

**Comment by ghostnetrn** [comment]
Oi @itxtoledo, obrigado pelo aviso. 

Testando o bot esse mês, peguei algumas oportunidades com ETH. Com BTC peguei algumas, mas de 0.2%.

Lucro: 1.62%
Buy: 6745.93, Sell: 6855.14

Em contato com o suporte, disseram que iam manter a opção de fazer arbitragem.

**Comment by TheRafaelSantos** [comment]
> offers
Opa itxtoledo! como vai? Ontem meu robô conseguiu efetuar uma oportunidade com BTC de 0.4% Mas por algum motivo após essa operação meu robô comprou BTC e na execussão de venda deu erro e logo após ficou a noite toda dando erro 502. Ainda estou investigando.

**Comment by ghostnetrn** [comment]
O erro 502 Bad Gateway significa que há uma falha ligada ao site, com problemas de comunicação entre servidores.

**Comment by TheRafaelSantos** [comment]
Opá Pessoal

Hoje deixei o robô rodando aqui e me deparei com um seccess on sell !!!!!! BOAAA

![image](https://user-images.githubusercontent.com/47929225/203597776-380b9f3d-3c04-4c4b-b728-edc0bb201a6a.png)

**Comment by ghostnetrn** [comment]
Só veja se esse valor de 0.05% já está considerando as taxas (0,2% por ordem). Nesse caso, 0.4% de taxas.

https://suporte.bitpreco.com/pt-BR/articles/3272366-taxas

**Comment by TheRafaelSantos** [comment]
Sim! Por enquanto coloquei pouco saldo apenas para testes. Teria alguma forma de quando da erro 502 o robô voltar a ativada automaticamente?

![image](https://user-images.githubusercontent.com/47929225/203631796-9c623b74-9042-4497-b8a0-8585b66697e0.png)

**Comment by ghostnetrn** [comment]
Tenta executar usando Docker ou o PM2. Tô usando Docker e até agora ok.

Depois vou refatorar o código e organizar melhor.

**Comment by p3bb4** [comment]
Olá, obrigado pelo bot.
Tentei executar mas não concluir.
Estou fazendo os testes no simulador.
![bit](https://user-images.githubusercontent.com/5108139/211595551-13799118-5365-4ea5-8040-90d45e87271d.PNG)

**Comment by k4m4h4l** [comment]
Alguem usando em 2023?
